### ISSUE TITLE
[Feature Request] Add support to Apple Music Windows 11 application

### ISSUE THREAD

**Issue by bigplayer-ai** [lx200916/desktop_plugin_server#3]
[Feature Request] Support Windows apple music windows 11 store Application.
Hey,
As a [Feature Request]  Can you Support [Windows apple music windows 11 store Application.](https://www.microsoft.com/en-us/p/apple-music/9pp5m2pj95gx):
[https://www.microsoft.com/en-us/p/apple-music/9pp5m2pj95gx](https://www.microsoft.com/en-us/p/apple-music/9pp5m2pj95gx
)

**Comment by lx200916** [comment]
Hi, this is a plugin for Cider and it functionality relys on the APIs offered by Cider.So for now we can not make it work on other music players that with no API support. Sorry 😭

**Comment by lx200916** [comment]
Okay I checked the App and found that Apple did not follow the Windows Media Control Guidelines(aka SMTC features), so that NONE of third party applications can get play state from it. So, bad news.
